## Note on 1.1 exercises
<h3>Product</h3>

<p>Compute $\frac{1}{2}\cdot\frac{2}{3}\cdot\frac{3}{4}\cdots\frac{99}{100}$.</p>

In [13]:
t = 1

for i in range(1, 99)
    t = t * i / ( i + 1 )
end

t

0.009999999999999998

<h3>Step argument in range   </h3>
<p> ​
In module 1.1 you had these two exercises: Compute $2+4+6+\cdots +100$ and $1+3+5+\cdots +99$, and you get to use a simple range object with some arithmetic to account for the fact that the needed values are not sequential integers.

    
There is the optional third argument to range called **step** that says how far to advance each time. we covered step and the subtypes of AbstractRange</p>

In [25]:
collect(2:2:10)

5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [27]:
collect(range(1,14, step=2))

7-element Vector{Int64}:
  1
  3
  5
  7
  9
 11
 13

In [29]:
collect(range(6,-2, step=-1))

9-element Vector{Int64}:
  6
  5
  4
  3
  2
  1
  0
 -1
 -2

In [36]:
t = sum( [ i for i in 2:2:101 ] )
print("2+4+6+...+100 =",t)

2+4+6+...+100 =2550

In [39]:
t = sum( [ i for i in range(1,100, step=2) ] )
print("1+3+5+...+99 =",t)

1+3+5+...+99 =2500

## Julia Booleans
The following Boolean operators are support on <b>Bool</b> types:
<pre>
!x	negation

x && y	short-circuiting and

x || y	short-circuiting or
</pre>
<p>Negation changes true to false and vice versa. The && and || operators in Julia correspond to logical “and” and “or” operations, respectively. However, they have an additional property of short-circuit evaluation: they don't necessarily evaluate their second argument. Some languages (like Python) refer to them as <b>and</b>  and <b>or</b>. Explicitly, this means that:

<li>In the expression a && b, the subexpression b is only evaluated if a evaluates to true.</li>
<li>In the expression a || b, the subexpression b is only evaluated if a evaluates to false</li>


</p>

In [42]:
x::Bool = true
y::Bool = false

println(x && y)
println(x || y)
println(x && !y)

false
true
true


### Bitwise Operators
supported on all primitive integer types. The bitwise operators compare the bits in the base two representation of numbers.

<pre>
    ~x	bitwise not
    
x & y	bitwise and
    
x | y	bitwise or
    
x ⊻ y	bitwise xor (exclusive or)
    
x ⊼ y	bitwise nand (not and)
    
x ⊽ y	bitwise nor (not or)
    
x >>> y	logical shift right
    
x >> y	arithmetic shift right
    
x << y	logical/arithmetic shift left
</pre>
Boolean operations without short-circuit evaluation can be done with the bitwise boolean operators, <b>& </b> and <b> |</b>

In [53]:
println(x & y)
println(x | y)
println(x & !y)

false
true
true


In [57]:
# 10 is 1010 base 2 = (1)2^3 + (0)2^2 + (1)2^1 + (0)2^0 = 8 + 0 + 2 + 0
# 4 is 0100 base 2 = (0)2^3 + (1)2^2 + (0)2^1 + (0)2^0 = 0 + 4 + 0 + 0

10 & 4 # 1010 & 0100 = 0000

0

In [58]:
10 | 4 # 1010 | 0100 = 1110

14

<h5>We'll revisit them more extensively when we get into Single- and Multi- Dimensional Arrays</h5>

Here is a sneak peek. Here we use <b>PyCall.jl</b> to call Python functions from the Julia language to compare the vectorization featured in NumPy and in Julia. 

You can import arbitrary Python modules from Julia, call Python functions (with automatic conversion of types between Julia and Python), define Python classes from Julia methods, and share large data structures between Julia and Python without copying them.

In [9]:
# initial pycall install and python path
# using Pkg
# Pkg.add("PyCall")
# ENV["PYTHON"] = "C:/Users/jph6366/.conda/envs/lf/python.exe"
# Pkg.build("PyCall")

using PyCall
np = pyimport("numpy")
a = np.array([true,false,true,false])
b = np.array([false,true,false,true])

a .& b # Vectorized (or element-wise) dot operator
# automatically performs element-by-element on arrays

# the same is acheived by defining Vectors in Julia
a = [true,false,true,false]
b = [false,true,false,true]

a .& b # performs a broadcast operation

4-element BitVector:
 0
 0
 0
 0

<h5>Broadcasting</h5>
<p>It is sometimes useful to perform element-by-element binary operations on arrays of different sizes, such as adding a vector to each column of a matrix. </p>

Julia provides broadcast, which expands singleton dimensions in array arguments to match the corresponding dimension in the other array without using extra memory, and applies the given function elementwise

Dotted operators such as .+ and .* are equivalent to broadcast calls, except that they fuse.

In [10]:
A = [1, 2, 3, 4, 5, 6]
# For example, if you compute 
2 .* A.^2 .+ sin.(A) # equivalent to  @. 2A^2 + sin(A)
#  it performs a single loop over A, computing 2a^2 + sin(a) for each element a of A.


6-element Vector{Float64}:
  2.8414709848078967
  8.909297426825681
 18.14112000805987
 31.243197504692073
 49.04107572533686
 71.72058450180107

### Numeric Comparisons
Standard comparison operations are defined for all the primitive numeric types:

<pre>==	equality
    
!=, ≠	inequality
    
<	less than
    
<=, ≤	less than or equal to
    
>	greater than
    
>=, ≥	greater than or equal to</pre>



In [12]:
println(2^7 < 7)
println(2/7 < 2)

false
true


In [13]:
println(2 ÷ 7 <= 0)
println(7 % 2 == 1)

true
true


<h5>Julia provides additional functions to test numbers for special values</h5>
<pre>isequal(x, y)	x and y are identical
isfinite(x)	x is a finite number
isinf(x)	x is infinite
isnan(x)	x is not a number
</pre>

### Exercises

Given x = True and y = False as assigned above, decide the truth values of the following expressions.  Create code cells to check your answers.

<ol>
    <li>!(x && y)</li>
    <li>!x && y</li>
    <li>!x && !y</li>
    <li>!x || !y</li>
    <li>x == (3 < 2)</li>
    <li>y || (3 > 2)</li>
</ol>

### Compound Expressions
Sometimes it is convenient to have a single expression which evaluates several subexpressions in order, returning the value of the last subexpression as its value. 

There are two Julia constructs that accomplish this: begin blocks and ; chains. The value of both compound expression constructs is that of the last subexpression. Here's an example of a begin block:

In [14]:
z = begin
    x = 1
    y = 2
    x + y
end
z

3

Since these are fairly small, simple expressions, they could easily be placed onto a single line, which is where the <b>;</b> chain syntax comes in handy:

In [15]:
z = ( x = 1; y = 2; x + y)

# but we can also write the begin in one line
begin x = 1; y = 2; x + y end

3

### Conditional Evaluation
Conditional evaluation allows portions of code to be evaluated or not evaluated depending on the value of a boolean expression. Here is the anatomy of the if-elseif-else conditional syntax:


In [ ]:
if x < y
    println("x is less than y")
elseif x > y
    println("x is greater than y")
else
    println("x is equal to y")
end

If the condition expression x < y is true, then the corresponding block is evaluated; 

otherwise the condition expression x > y is evaluated, and if it is true, the corresponding block is evaluated; 

if neither expression is true, the else block is evaluated. Here it is in action:

### Example

Compute $2^2+3^3+4^2+5^3+6^2+\cdots +99^3$

**Plan**

<ul>
    <li>Note that the even numbers are squared and the odd ones are cubed.  The if/else structure lets us do different operations for the even and odd cases.</li>
    <li>It is possible to handle the even and odd cases in two separate loops then add the results, but the point is to illustrate if/else.</li>
    <li>Use a for loop with range(2,99).</li>
    <li>Use a variable initialized before the for loop to accumulate the sum.</li>
    <li>In the body of the loop, <b>if</b> the item is even, then square, <b>else</b> cube, then add to the accumulator.</li>
    <li>A number t is even if and only if the remainder when you divide by 2 is zero.  So t%2 == 0 means t is even.</li>
</ul>

**Even vs Odd**

Let n be an integer.

n%2 is the remainder when n is divided by 2, so it must be either 0 or 1.

* If n%2 == 0, then n is even
* If n%2 == 1, then n is odd.

In [23]:
total = 0

for i in range(2,9)
    if i%2 == 0
        total = total + i^2
    else
        total = total + i^3
    end
end
total

1344

In [25]:
myvec = ["SC", "NC", "GA", "VA"]

for s in myvec
    if s == "NC"
        println("North Carolina")
    else
        if s == "SC"
            println("South Carolina")
        else
            if s == "GA"
                println("Georgia")
            else
                println("NotFound")
            end
        end
    end
end

South Carolina
North Carolina
Georgia
NotFound


In this example we checked for four cases.  It is quite common to have more than two possible cases, but writing a lot of else-if combinations can be cumbersome. elseif is a shortcut for the else-if combination.

In [24]:
for s in myvec
    if s == "NC"
        println("North Carolina")
    elseif s == "SC"
        println("South Carolina")
    elseif s == "GA"
        println("Georgia")
    else
        println("NotFound")
    end
end

South Carolina
North Carolina
Georgia
NotFound


<h5> NOTE: if blocks return a value. 
    
The value is simply the retun value of the last executed statement in the branch that was chosen </h5>

<p>Unlike C, MATLAB, Perl, Python, and Ruby – but like Java, and a few other stricter, typed languages – it is an error if the value of a conditional expression is anything but true or false:</p>

In [26]:
if 1
    println("true")
end

LoadError: TypeError: non-boolean (Int64) used in boolean context

<h4>The so-called "ternary operator", ?:, is closely related to the if-elseif-else syntax, but is used where a conditional choice is required</h4>

<h5>the choice is between single expression values is required, as opposed to conditional execution of longer blocks of code.</h5>

<p>It gets its name from being the only operator in most languages taking three operands</p>

In [31]:
  #############
 # a ? b : c #
#############

# The expression a, before the ?, is a condition expression

# The ternary operation evaluates:

# the expression b, before the :
# , if the condition a is true 

# or the expression c, after the :
# , if condition a is false

x = 1; y = 2;
println(x < y ? "less than" : "not less than")
y = 0;
println(x < y ? "less than" : "not less than")

less than
not less than


## Random Numbers
Support for generating random numbers. Provides rand, randn, AbstractRNG, MersenneTwister, and RandomDevice.
<p>The PRNGs (pseudorandom number generators) exported by the Random package are:

<li><b>TaskLocalRNG:</b> a token that represents use of the currently active Task-local stream, deterministically seeded from the parent task, or by RandomDevice (with system randomness) at program start</li>
<li><b>Xoshiro:</b> generates a high-quality stream of random numbers with a small state vector and high performance using the Xoshiro256++ algorithm </li>
<li><b>RandomDevice:</b> for OS-provided entropy. This may be used for cryptographically secure random numbers (CS(P)RNG).</li>
<li><b>MersenneTwister:</b> an alternate high-quality PRNG which was the default in older versions of Julia, and is also quite fast, but requires much more space to store the state vector and generate a random sequence.</li>

</p>

<p> Most functions related to random generation accept an optional <b>AbstractRNG</b> object as first argument. Some also accept dimension specifications dims...(or given as a tuple) to generate arrays of random values.</p>


### Random Generation functions
<h3>rand</h3>
<p>Pick a random element or array of random elements from the set of values </p>

<h3>randn</h3>
<p>Generate a normally-distributed random number with mean 0 and standard deviation 1. </p>

In [32]:
rand(Int, 2)

2-element Vector{Int64}:
 -1564900595504423461
 -4410092618210346130

In [35]:
rand(60:600)

184

In [37]:
rand(A) # A is Array from earlier

3

In [41]:
rand("Hello")

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

In [39]:
# Generating a single random number (with the default Float64 type)
randn()

0.27668345136341804

In [40]:
# Generating a matrix of normal random numbers (with the default Float64 type)
randn(2,3)

2×3 Matrix{Float64}:
 -1.56918    0.995545  -0.709959
 -0.547901  -1.1211     1.70931

In [ ]:
?rand #  For help on a specific function or macro, type ? followed by its name

or example, rand(1:6) will return a random integer between 1 and 6 **inclusive**, so you could use this to simulate the roll of a standard die.

### Example

Use a for loop to approximate the probability of rolling an eight with two standard dice.  **The exact value is $\frac{5}{36}\approx 0.1389$**.

A standard die is a cube with six faces, and the faces show dots representing the numbers one through six.  So to simulate the roll of two dice we call the function rand(1:6) two times.

**Question**  We are interested in the sum of the values on the two dice, and that sum will be between two and twelve.  Instead of calling rand(1:6) twice, would it be OK to call rand(1:12) one time?  Why?

**Plan**

<ul>
    <li>The experiment is to roll two dice once and add the face values.  The event we are interested in is that the sum is exactly eight.  We need to simulate the experiment a large number of times and count the number of times we roll an eight.</li>
    <li>I will set the variable trials equal to 10,000 and execute the experiment that many times, keeping a running total of the times I roll an eight.</li>
    <li>Finally return the total divided by trials for the average.
</ul>


In [92]:
# each time a new julia session is started, the first call to rand() produces a different result
# When the Random module is loaded, the default RNG is randomly seeded, 
using Random 
Random.seed!(42); # Reseed the random number generator
# ! indicates that the function modifies its arguments, which isn't enforced by Julia

total = 0 # of times event occurs
trials = 10000 # of times to run the experiment

for _ in 1:trials
    roll = rand(1:6) + rand(1:6)
    if roll == 8
        total+=1
    end
end

total/trials


0.1423

### Example

The experiment consists of flipping a fair coin ten times.  The event we are interested in is that the coin shows heads at most three times.  Approximate the probability of this event.  

**The exact probability is $176/1024 = 0.171875$**.

**Plan**

<ul>
    <li>In this case I want random integers that are either 0 or 1, so I use random.randint(0,1).  For this problem I will let 1 stand for a flip of heads.</li>
    <li>This problem is quite similar to the dice probability problem.  I will use a variable trials that holds the number of times to run the experiment and I will use a variable total to keep track of the number of successes, which means the number of times I got at most three heads.</li>
</ul>

In [99]:
Random.seed!(1); # Reseed the random number generator

total = 0 
trials = 10000

for i in 1:trials
    """
    Need to call the function rand(0:1) ten times.  Since getting 1 corresponds to heads,
    I just add the ten numbers together to count the number of heads.  Tails corresponds to getting
    0 so it does not add to the result.
    I could type out rand(0:1) ten times and add them together, but this is a pain!
    So I will use another for loop to simulate the ten coin flips.
    """
    heads = sum([ rand(0:1) for j in 1:10]) # flip ten times and sum the results
    if heads <= 3
        total += 1
    end
end

total/trials

0.1653

### Example: Generating values from a type

>There are ten cards in a bag and the cards are labeled 1 through 10.  Select three cards from the bag without replacement.  What is the probability that all three cards have labels less than or equal to 5?  **The exact probability is $\frac{1}{12} = 0.08\overline{3}$**. 



In [145]:
rand(1:10, 3) # collection of values, and dims

3-element Vector{Int64}:
 9
 9
 8

The result is a vector of the items in the order they were drawn.

**Plan**

<ul>
    <li>As usual, I let trials be the number of times to run the experiment, and total is the number of times the event occurs, in other words, the number of times all three cards drawn have label &lt;= 5.</li>
    <li>To check for success, look at each of the three cards drawn and check they are all &lt;= 5.</li>
</ul>

In [147]:
Random.seed!(143)

total = 0 
trials = 10000

for _ in 1:trials
    draw = rand(1:10, 3)

    if draw[1] <= 5 && draw[2] <= 5 && draw[3] <= 5
        total += 1
    end
end

total / trials

0.1244

## Exercises

<ol>
    <li>Rolling two dice, what is the probablity of getting either a 7 or an 11?<p><p><b>Exact probability is $\frac{2}{9}\approx 0.2222$</b>.</li>
    <li>Flip a fair coin 20 times.  What is the probability that heads turns up either less than or equal to four times or greater than or equal to 16 times?<p><p><b>Exact probability is $\frac{12392}{2^{20}}\approx 0.01182$</b>.</li>
    <li>A bag contains fifteen marbles, five red, five green, and five blue.  Draw three at random without replacement.  What is the probability that all three are blue?<p><p><b>Exact probability is $\frac{2}{91}\approx 0.02198$</b>.</li>
    <li>Same bag of marbles, draw two at random without replacement. What is the probability that the two marbles are the same color? <p><b>Exact probability is $\frac{2}{7}\approx 0.2857$</b></li>
<ol>
    