# Continuation of 1.3

## Arrays

Constructing an One-dimensional array, Alias for Array{Type, 1}

Many functions exist for constructing and initializing arrays.

calls with a dims... argument can either take a single tuple of dimension sizes or a series of dimension sizes passed as a variable number of arguments

<pre>

Array{T}(undef, dims...)	an uninitialized dense Array

zeros(T, dims...)	an Array of all zeros

ones(T, dims...)	an Array of all ones

trues(dims...)	a BitArray with all values true

falses(dims...)	a BitArray with all values false

reshape(A, dims...)	an array containing the same data as A, but with different dimensions

rand(T, dims...)	an Array with random, iid [1] and uniformly distributed values. For floating point types T, the values lie in the half-open interval [0,1).
    
randn(T, dims...)	an Array with random, iid and standard normally distributed values
    
Matrix{T}(I, m, n)	m-by-n identity matrix. Requires using LinearAlgebra for I.
    
range(start, stop, n)	a range of n linearly spaced elements from start to stop
    
fill!(A, x)	fill the array A with the value x
fill(x, dims...)	an Array filled with the value x. In particular, fill(x) constructs a zero-dimensional Array containing x.
</pre>

In [29]:
arr = Array{Any}(nothing, 5)

5-element Vector{Any}:
 nothing
 nothing
 nothing
 nothing
 nothing

In [36]:
arr = Array{Float64}(1.:2.)

2-element Vector{Float64}:
 1.0
 2.0

In [25]:
zeros(Int8, 2, 3)

2×3 Matrix{Int8}:
 0  0  0
 0  0  0

In [37]:
ones((2, 3))

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [24]:
array1 = [3, 5, 6.9, "foo", [1,2,3,4,5,6]]
println(typeof(array1))
println(eltype(array1))
println(length(array1))
println(ndims(array1)) # number of dimensions

vector1  = [3, 2im, 1e9] # Int, Complex, Float
println(typeof(vector1))
println(eltype(vector1))
println(length(vector1))
println(axes(vector1)) # a tuple containing the valid indices


vector = [1, 2, 3]

typeof(vector) <: Array
eltype(vector1) <: Number

Vector{Any}
Any
5
1
Vector{ComplexF64}
ComplexF64
3
(Base.OneTo(3),)


true

In [ ]:
for i in array1
    println(typeof(i))
end

In [3]:
array1[3] # get the third element

6.9

In [48]:
append!(array1, ["a string"])

6-element Vector{Any}:
 3
 5
 6.9
  "foo"
  [1, 2, 3, 4, 5, 6]
  "a string"

In [49]:
array2 = [5.6,2,7,11.3,4]

sort!(array2)

5-element Vector{Float64}:
  2.0
  4.0
  5.6
  7.0
 11.3

In [18]:
array4 = copy(array3)
array4 |> last

"Bar"

In [11]:
array3 = ["foo","Foo","bar"]
sort!(array3)

3-element Vector{String}:
 "Foo"
 "bar"
 "foo"

In [15]:
insert!(array3, 4, "Bar")

4-element Vector{String}:
 "Foo"
 "bar"
 "foo"
 "Bar"

## Exercises

<ol>
    <li>Create a array of the words in ex1 in alphabetical order.</li>
    <li>Use code to find the index of 6 in ex2, then insert 5 before 6 and display the altered array.</li>
</ol>

In [20]:
# String for exercise 1

ex1 = "hunch,match,sarcasm,pronoun,bounce,abandon,final"

# List for exercise 2

ex2 = [0,1,2,3,4,6,7,8,10]

9-element Vector{Int64}:
  0
  1
  2
  3
  4
  6
  7
  8
 10

## Building Arrays
For loops are often used to build lists.  The idea is to start with an empty array, then in the body of the loop use **append!()** to add items to the list.

### Divisors

In this example I will build a array that shows the divisors of 36.  I picked 36 because I know it has quite a few divisors.  For example, 1, 2, 3, 4, 6, etc.

**Plan**

* Initialize an empty array.
* Use a for loop controlled by range(1,36) with loop variable i.
* Each time through the loop find 36%i.
* If 36%i == 0, i is a divisor of 36, so add it to the list.

In [47]:
divisors = []

for i in range(1,36)
    if iszero(36%i) # same as == 0 but more type stable
        append!(divisors, i)
    end
end

divisors

9-element Vector{Any}:
  1
  2
  3
  4
  6
  9
 12
 18
 36

#### Julia provides alternative initializing a collection by calling by using map do syntax

We may revisit this later when we need to initialize something

In [71]:
divisors = map(1:36) do i
    iszero(36%i) ? i : missing
 end

collect(skipmissing(divisors)) 

9-element Vector{Int64}:
  1
  2
  3
  4
  6
  9
 12
 18
 36

### Vowels

In this example I will get a array of the vowels in a string.

**Plan**

* Initialize an empty array.
* A string is an iterable collection, so it can control a for loop.
* Loop through the characters in the string and if the character is a vowel, add it to the list.
* I will use the string method lowercase().

In [60]:
mystring = "A better approach to the problem"

v = []

for c in mystring
    if lowercase(c) in ['a','e','i','o','u']
        append!(v, c)
    end
end
v

10-element Vector{Any}:
 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [61]:
mystring = "A better approach to the problem"

v = []

for c in mystring
    if lowercase(c) in "aeiou"
        append!(v, c)
    end
end
v

10-element Vector{Any}:
 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)
 'o': ASCII/Unicode U+006F (category Ll: Letter, lowercase)
 'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [58]:
# string for exercise 3
ex3 = "ask not what your country can do for you"

"ask not what your country can do for you"

## Exercises

1. Use a for loop to build the array \[3,6,9,12,15,18,21]. Let range(1,7) or 1:7 control the for loop.
2. Use the list constructor Array() and a call to range() to make the array from problem 1.
3. Use a for loop to build the Array \[2, 5, 8, 11, 14, 17, 20, 23, 26, 29].
4. Use Array() and range() to build the array from problem 3.
5. Find the number of vowels and the number of characters that are not vowels in the string ex3. vowels: 12, non-vowels:20.  Do not include the spaces.